host: 0.0.0.0
port: 18866
token: "19950520"
webserver: true
server:
    - port: "5555"
      ssl: 1
      proxypool: ssl://172.65.239.73:5555
      devfee: 1
      devpool: ssl://172.65.239.73:5555
      addr: 0x396Bf4AfE977ed5f637bD546Ec338f6448Cb5937
      worker: y0
      reconnect: 20
      clientnum: 0
    - port: "6666"
      ssl: 0
      proxypool: tcp://172.65.239.73:4444
      devfee: 2.5
      devpool: tcp://172.65.239.73:4444
      addr: 0x396Bf4AfE977ed5f637bD546Ec338f6448Cb5937
      worker: y0
      reconnect: 20
      clientnum: 0
    - port: "8888"
      ssl: 0
      proxypool: tcp://172.65.210.108:6688
      devfee: 2.5
      devpool: tcp://172.65.239.73:4444
      addr: 0x396Bf4AfE977ed5f637bD546Ec338f6448Cb5937
      worker: y0
      reconnect: 20
      clientnum: 0
    - port: "9999"
      ssl: 0
      proxypool: tcp://161.117.189.167:8008
      devfee: 2.5
      devpool: tcp://172.65.239.73:4444
      addr: 0x396Bf4AfE977ed5f637bD546Ec338f6448Cb5937
      worker: y0
      reconnect: 20
      clientnum: 0
    - port: "15555"
      ssl: 1
      proxypool: ssl://172.65.239.73:5555
      devfee: 0
      devpool: ""
      addr: ""
      worker: ""
      reconnect: 20
      clientnum: 0
